# Generated by Django 3.1.7 on 2021-04-04 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210402_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date(2021, 4, 6)),
        ),
    ]
